#!/usr/bin/env bash

if [ -d $1 ]; then
    cd $1
fi

for file in $(git ls-files) ; do
    if [[ $(file $file) == *ASCII* ]]; then
        echo $file
        sed -i '' $'s/^    /\t/g' $file
    fi
done
